package forge.adventure.scene;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.g2d.TextureRegion;
import com.badlogic.gdx.utils.Array;
import com.google.common.collect.ImmutableList;
import forge.Forge;
import forge.Graphics;
import forge.LobbyPlayer;
import forge.card.CardRenderer;
import forge.card.CardRenderer.CardStackPosition;
import forge.card.CardZoom;
import forge.adventure.character.EnemySprite;
import forge.adventure.character.PlayerSprite;
import forge.adventure.data.*;
import forge.adventure.player.AdventurePlayer;
import forge.adventure.stage.GameHUD;
import forge.adventure.stage.IAfterMatch;
import forge.adventure.util.AdventureEventController;
import forge.adventure.util.Config;
import forge.adventure.util.Current;
import forge.adventure.util.Reward;
import forge.assets.FBufferedImage;
import forge.assets.FSkin;
import forge.card.ColorSet;
import forge.deck.*;
import forge.game.card.CardView;
import forge.game.GameRules;
import forge.game.GameType;
import forge.game.player.Player;
import forge.game.player.RegisteredPlayer;
import forge.game.GameOutcome;
import forge.gamemodes.match.HostedMatch;
import forge.gamemodes.quest.QuestUtil;
import forge.localinstance.properties.ForgePreferences;
import forge.model.FModel;
import forge.gui.FThreads;
import forge.gui.interfaces.IGuiGame;
import forge.item.IPaperCard;
import forge.item.PaperCard;
import forge.gamemodes.match.LobbySlot;
import forge.gamemodes.match.LobbySlotType;
import forge.gamemodes.net.adventure.AdventureNetSession;
import forge.gamemodes.net.server.FServerManager;
import forge.gamemodes.net.server.ServerAdventureLobby;
import forge.player.GamePlayerUtil;
import forge.player.LobbyPlayerHuman;
import forge.player.PlayerControllerHuman;
import forge.screens.FScreen;
import forge.screens.LoadingOverlay;
import forge.screens.TransitionScreen;
import forge.screens.match.MatchController;
import forge.sound.MusicPlaylist;
import forge.sound.SoundSystem;
import forge.toolbox.FCardPanel;
import forge.toolbox.FDisplayObject;
import forge.toolbox.FOptionPane;
import forge.util.Aggregates;
import forge.util.StreamUtil;
import org.apache.commons.lang3.tuple.Pair;

import java.util.*;

/**
 * DuelScene
 * Forge screen scene that contains the duel screen
 */
public class DuelScene extends ForgeScene {
    private static DuelScene object;

    public static DuelScene instance() {
        if (object == null)
            object = new DuelScene();
        return object;
    }

    //GameLobby lobby;
    HostedMatch hostedMatch;
    EnemySprite enemy;
    PlayerSprite player;
    RegisteredPlayer humanPlayer;
    private EffectData dungeonEffect;
    Deck playerDeck;
    boolean chaosBattle = false;
    boolean callbackExit = false;
    /** Enemy data received via BATTLE_INIT on the client; used to generate rewards on BATTLE_END. */
    private EnemyData networkEnemyData = null;
    /** Set when the client's GameEnd() fires so late-arriving BATTLE_END can still show rewards. */
    private boolean networkClientExited = false;
    /** Rewards generated by BATTLE_END, consumed by GameEnd() to route to RewardScene. */
    private Array<Reward> pendingClientRewards = null;
    boolean arenaBattleChallenge = false;
    boolean isArena = false;
    AdventureEventData eventData;
    final int enemyAvatarKey = 90001;
    final int playerAvatarKey = 90000;
    FOptionPane bossDialogue;
    List<IPaperCard> playerExtras = new ArrayList<>();
    List<IPaperCard> AIExtras = new ArrayList<>();


    private DuelScene() {
    }


    @Override
    public void dispose() {
    }

    public boolean hasCallbackExit() {
        return callbackExit;
    }

    public void GameEnd() {
        if (hostedMatch == null) {
            // Network client — consume any rewards queued by BATTLE_END and route accordingly.
            networkClientExited = true;
            final Array<Reward> clientRewards = pendingClientRewards;
            pendingClientRewards = null;
            endRunnable = () -> Gdx.app.postRunnable(() -> {
                GameHUD.getInstance().updateBGM();
                Forge.clearTransitionScreen();
                Forge.clearScreenStack();
                if (clientRewards != null && !clientRewards.isEmpty()) {
                    RewardScene.instance().loadRewards(clientRewards, RewardScene.Type.Loot, null);
                    Forge.switchScene(RewardScene.instance());
                } else {
                    GameScene.instance().enter();
                }
            });
            exitDuelScene();
            return;
        }
        //TODO: Progress towards applicable Adventure quests also needs to be reported here.
        if (eventData != null)
            eventData.nextOpponent = null;
        boolean winner = false;
        List<PaperCard> anteWonCards = Collections.emptyList();
        List<PaperCard> anteLostCards = Collections.emptyList();
        try {
            // Team-based win check.  In single-player vs an AI opponent there's exactly one
            // human, so the single-player code path (humanPlayer == getWinner()) worked.
            // In adventure co-op the host and every client are on team 0 and the AI is on team 1;
            // getMatch().getWinner() returns *one* of the team-0 winners (iteration order of the
            // playerRating map), which is often the client rather than the host — so the host
            // would be flagged as loser, the dungeon would kick them out, and the BATTLE_END
            // broadcast would carry winner=false so the client never generated rewards either.
            // Compare winning team to humanPlayer's team instead.
            final GameOutcome outcome = hostedMatch.getGame().getMatch().getLastOutcome();
            winner = outcome != null && outcome.getWinningTeam() == humanPlayer.getTeamNumber();

            //Persists expended (or potentially gained) shards back to Adventure
            if (eventData == null || eventData.eventRules.allowsShards) {
                List<PlayerControllerHuman> humans = hostedMatch.getHumanControllers();
                {
                    if (humans.size() == 1) {
                        Current.player().setShards(humans.get(0).getPlayer().getNumManaShards());
                    }
                }
            }

            // Mostly for ante handling, but also blacker lotus
            GameOutcome.AnteResult anteResult = hostedMatch.getAnteResult(humanPlayer);
            if (anteResult != null) {
                if (eventData != null) {
                    //In an event. Apply the ante result to the current event deck.
                    eventData.registeredDeck.getOrCreate(DeckSection.Sideboard).add(anteResult.wonCards);
                    if(eventData.rewardDeck != null)
                        eventData.rewardDeck.getOrCreate(DeckSection.Sideboard).add(anteResult.wonCards);
                    for(PaperCard card : anteResult.lostCards) {
                        eventData.registeredDeck.removeAnteCard(card);
                        if(eventData.rewardDeck != null)
                            eventData.rewardDeck.removeAnteCard(card);
                    }
                    //Could also add the cards to the opponent's pool, but their games aren't simulated and they never edit their decks.
                }
                else {
                    for (PaperCard card : anteResult.wonCards) {
                        Current.player().addCard(card);
                    }
                    for (PaperCard card : anteResult.lostCards) {
                        // We could clean this up by trying to combine all the lostCards into a mapping, but good enough for now
                        Current.player().removeLostCardFromPools(card);
                    }
                }
                anteWonCards = new ArrayList<>(anteResult.wonCards);
                anteLostCards = new ArrayList<>(anteResult.lostCards);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        String enemyName = enemy.getName();
        String insult = enemy.getBossInsult();
        boolean showMessages = enemy.getData().boss || (enemy.getData().copyPlayerDeck && Current.player().isUsingCustomDeck());
        Current.player().clearBlessing();

        boolean finalWinner = winner;
        boolean isBossLoss = (chaosBattle || showMessages) && !finalWinner;
        boolean hasAnteResults = !anteWonCards.isEmpty() || !anteLostCards.isEmpty();

        // No popups needed, preserve original behavior
        if (!hasAnteResults && !isBossLoss) {
            afterGameEnd(enemyName, finalWinner);
            return;
        }

        // Build popup chain: ante results -> boss dialogue -> exit
        callbackExit = true;
        Runnable exitChain = () -> {
            afterGameEnd(enemyName, finalWinner);
            exitDuelScene();
        };

        Runnable afterAnte;
        if (isBossLoss) {
            afterAnte = () -> {
                final FBufferedImage fb = getFBEnemyAvatar();
                String bossInsultMsg = insult != null ? insult
                        : Forge.getLocalizer().getMessage("AdvBossInsult" + Aggregates.randomInt(1, 44));
                bossDialogue = createFOption(bossInsultMsg,
                        enemyName, fb, () -> {
                            exitChain.run();
                            fb.dispose();
                        });
                FThreads.invokeInEdtNowOrLater(() -> bossDialogue.show());
            };
        } else {
            afterAnte = exitChain;
        }

        if (hasAnteResults) {
            showAnteResults(anteWonCards, anteLostCards, afterAnte);
        } else {
            afterAnte.run();
        }
    }

    Runnable endRunnable = null;

    /**
     * Serialize a single Reward to a compact string for network transmission.
     * Format: "Type:value", e.g. "Gold:25", "Card:Llanowar Elves", "Shards:5".
     */
    static String serializeReward(final Reward r) {
        if (r == null) return null;
        switch (r.getType()) {
            case Gold:   return "Gold:" + r.getCount();
            case Life:   return "Life:" + r.getCount();
            case Shards: return "Shards:" + r.getCount();
            case Card:
                if (r.getCard() == null) return null;
                return (r.isNoSell() ? "CardNoSell:" : "Card:") + r.getCard().getName();
            case Item:
                if (r.getItem() == null || r.getItem().name == null) return null;
                return "Item:" + r.getItem().name;
            default: return null;
        }
    }

    /**
     * Deserialize a reward string (produced by serializeReward) back to a Reward object.
     * Called on the client side from the BATTLE_END handler.
     */
    public static Reward deserializeReward(final String s) {
        if (s == null || s.isEmpty()) return null;
        final int colon = s.indexOf(':');
        if (colon < 0) return null;
        final String type  = s.substring(0, colon);
        final String value = s.substring(colon + 1);
        try {
            switch (type) {
                case "Gold":   return new Reward(Integer.parseInt(value));
                case "Life":   return new Reward(Reward.Type.Life,   Integer.parseInt(value));
                case "Shards": return new Reward(Reward.Type.Shards, Integer.parseInt(value));
                case "Card": {
                    final PaperCard card = FModel.getMagicDb().getCommonCards().getCard(value);
                    return card != null ? new Reward(card) : null;
                }
                case "CardNoSell": {
                    final PaperCard card = FModel.getMagicDb().getCommonCards().getCard(value);
                    return card != null ? new Reward(card, true) : null;
                }
                case "Item": {
                    final ItemData item = ItemListData.getItem(value);
                    return item != null ? new Reward(item) : null;
                }
                default: return null;
            }
        } catch (final Exception e) {
            System.err.println("[AdventureMP] deserializeReward failed for '" + s + "': " + e.getMessage());
            return null;
        }
    }

    void afterGameEnd(String enemyName, boolean winner) {
        Forge.advFreezePlayerControls = winner;
        final AdventureNetSession endNetSession = AdventureNetSession.getInstance();
        if (endNetSession.isActiveHost()) {
            // Generate rewards on the host using the full EnemySprite.getRewards() logic
            // (which handles chaos battles, sprite-level rewards, and enemy-deck card pulls)
            // and serialize them so clients receive exact reward items — not a re-roll.
            String[] rewardStrings = null;
            if (winner && enemy != null) {
                final Array<Reward> clientRewards = enemy.getRewards();
                final java.util.List<String> parts = new java.util.ArrayList<>();
                for (final Reward r : clientRewards) {
                    final String rs = serializeReward(r);
                    if (rs != null) parts.add(rs);
                }
                rewardStrings = parts.toArray(new String[0]);
            }
            endNetSession.serverLobby.onBattleEnd(winner, rewardStrings);
        }
        endRunnable = () -> Gdx.app.postRunnable(() -> {
            GameHUD.getInstance().updateBGM();
            dungeonEffect = null;
            callbackExit = false;
            Forge.clearTransitionScreen();
            Forge.clearScreenStack();
            Forge.advFreezePlayerControls = false;
            Scene last = Forge.switchToLast();
            Current.player().getStatistic().setResult(enemyName, winner);

            if (last instanceof IAfterMatch) {
                ((IAfterMatch) last).setWinner(winner, isArena);
            }
        });
    }

    public void exitDuelScene() {
        Forge.setTransitionScreen(new TransitionScreen(endRunnable, Forge.takeScreenshot(), false, false));
    }

    /** Returns the enemy data sent by the host in BATTLE_INIT; used to generate client rewards. */
    public EnemyData getNetworkEnemyData() {
        return networkEnemyData;
    }

    /**
     * Called from the BATTLE_END handler with rewards the client earned.
     * If GameEnd() has already run (race condition), switches to RewardScene directly.
     */
    public void setPendingClientRewards(final Array<Reward> rewards) {
        if (rewards == null || rewards.isEmpty()) return;
        pendingClientRewards = rewards;
        if (networkClientExited) {
            // GameEnd() already fired — rewards arrived late. Jump to RewardScene from wherever we are.
            Gdx.app.postRunnable(() -> Gdx.app.postRunnable(() -> {
                RewardScene.instance().loadRewards(rewards, RewardScene.Type.Loot, null);
                Forge.switchScene(RewardScene.instance());
            }));
        }
    }

    /**
     * Called on adventure clients when BATTLE_INIT arrives from the server.
     * Opens the match screen; game state is set up by GameClientHandler once
     * the server broadcasts openView to this client.
     */
    public void enterAsNetworkClient(final Object enemyDataPayload) {
        networkEnemyData = (enemyDataPayload instanceof EnemyData) ? (EnemyData) enemyDataPayload : null;
        networkClientExited = false;
        pendingClientRewards = null;
        SoundSystem.instance.stopBackgroundMusic();
        super.enter();
    }

    private FOptionPane createFOption(String message, String title, FBufferedImage icon, Runnable runnable) {
        return new FOptionPane(message, null, title, icon, null, ImmutableList.of(Forge.getLocalizer().getMessage("lblOK")), -1, result -> {
            if (runnable != null)
                runnable.run();
        });
    }

    private void showAnteResults(List<PaperCard> wonCards, List<PaperCard> lostCards, Runnable onDone) {
        // Show won cards one at a time, then lost cards, then continue
        showAnteCardsSequentially(wonCards, 0, true, () ->
            showAnteCardsSequentially(lostCards, 0, false, onDone));
    }

    private void showAnteCardsSequentially(List<PaperCard> cards, int index, boolean won, Runnable onDone) {
        if (index >= cards.size()) {
            onDone.run();
            return;
        }
        PaperCard card = cards.get(index);
        Runnable next = () -> showAnteCardsSequentially(cards, index + 1, won, onDone);
        showAnteCardPopup(won ? "Card Gained" : "Card Lost", card, won, next);
    }

    private void showAnteCardPopup(String title, PaperCard card, boolean won, Runnable onDone) {
        CardView cardView = CardView.getCardForUi(card);

        FDisplayObject cardDisplay = new FDisplayObject() {
            @Override
            public boolean tap(float x, float y, int count) {
                CardZoom.show(cardView);
                return true;
            }
            @Override
            public boolean longPress(float x, float y) {
                CardZoom.show(cardView);
                return true;
            }
            @Override
            public void draw(Graphics g) {
                float h = getHeight();
                float w = h / FCardPanel.ASPECT_RATIO;
                float xPos = (getWidth() - w) / 2;
                CardRenderer.drawCard(g, cardView, xPos, 0, w, h, CardStackPosition.Top, true);
            }
        };
        cardDisplay.setHeight(Forge.getScreenHeight() / 3);

        int ownedCount = Current.player().getCollectionCards(true).count(card);
        String ownedInfo = won
                ? (ownedCount == 0 ? " (New!)" : " (Owned: " + ownedCount + ")")
                : (ownedCount > 0 ? " (Remaining: " + ownedCount + ")" : "");
        String message = card.getName() + ownedInfo;
        List<String> buttons;
        if (won && eventData == null) {
            int sellPrice = Current.player().cardSellPrice(card);
            buttons = sellPrice > 0
                    ? ImmutableList.of(Forge.getLocalizer().getMessage("lblOK"), "Auto-Sell (" + sellPrice + " gold)")
                    : ImmutableList.of(Forge.getLocalizer().getMessage("lblOK"));
        } else {
            buttons = ImmutableList.of(Forge.getLocalizer().getMessage("lblOK"));
        }

        FOptionPane popup = new FOptionPane(message, null, title, null, cardDisplay, buttons, 0, result -> {
            if (won && result == 1) {
                Current.player().autoSellCards.add(card);
            }
            if (onDone != null) onDone.run();
        });
        FThreads.invokeInEdtNowOrLater(popup::show);
    }

    void addEffects(RegisteredPlayer player, Array<EffectData> effects) {
        if (effects == null) return;
        //Apply various combat effects.
        int lifeMod = 0;
        int changeStartCards = 0;
        int extraManaShards = 0;
        Array<IPaperCard> startCards = new Array<>();
        Array<IPaperCard> startCardsInCommandZone = new Array<>();

        for (EffectData data : effects) {
            lifeMod += data.lifeModifier;
            changeStartCards += data.changeStartCards;
            startCards.addAll(data.startBattleWithCards());
            startCardsInCommandZone.addAll(data.startBattleWithCardsInCommandZone());
            extraManaShards += data.extraManaShards;
        }
        player.addExtraCardsOnBattlefield(startCards);
        player.addExtraCardsInCommandZone(startCardsInCommandZone);
        if (lifeMod != 0)
            player.setStartingLife(Math.max(1, lifeMod + player.getStartingLife()));
        player.setStartingHand(player.getStartingHand() + changeStartCards);
        player.setManaShards((player.getManaShards() + extraManaShards));
        player.setEnableETBCountersEffect(true); //enable etbcounters on starting cards like Ring of Three Wishes, etc...
    }

    public void setDungeonEffect(EffectData E) {
        dungeonEffect = E;
    }

    @Override
    public void enter() {
        SoundSystem.instance.stopBackgroundMusic();
        GameType mainGameType;
        boolean isDeckMissing = false;
        String isDeckMissingMsg = "";
        if (eventData != null && eventData.eventRules != null) {
            mainGameType = eventData.eventRules.gameType;
        } else if (AdventurePlayer.current().isCommanderMode()){
            mainGameType = GameType.Commander;
        } else {
            mainGameType = GameType.Adventure;
        }
        Set<GameType> appliedVariants = EnumSet.of(mainGameType);

        AdventurePlayer advPlayer = Current.player();

        List<RegisteredPlayer> players = new ArrayList<>();

        applyAdventureDeckRules(mainGameType.getDeckFormat());
        int playerCount = 1;
        EnemyData currentEnemy = enemy.getData();
        for (int i = 0; i < 8 && currentEnemy != null; i++) {
            playerCount++;
            currentEnemy = currentEnemy.nextEnemy;
        }
        final AdventureNetSession netSession = AdventureNetSession.getInstance();
        if (netSession.isActiveHost()) {
            for (int si = 1; si < netSession.serverLobby.getNumberOfSlots(); si++) {
                if (netSession.serverLobby.getSlot(si).getType() == LobbySlotType.REMOTE)
                    playerCount++;
            }
        }

        humanPlayer = RegisteredPlayer.forVariants(playerCount, appliedVariants, playerDeck, null, false, null, null);
        LobbyPlayer playerObject = GamePlayerUtil.getGuiPlayer();
        FSkin.getAvatars().put(playerAvatarKey, advPlayer.avatar());
        playerObject.setAvatarIndex(playerAvatarKey);
        humanPlayer.setPlayer(playerObject);
        humanPlayer.setTeamNumber(0);
        humanPlayer.setStartingLife(eventData != null ? eventData.eventRules.startingLife : advPlayer.getLife());
        if (eventData == null || eventData.eventRules.allowsShards)
            humanPlayer.setManaShards(advPlayer.getShards());

        Array<EffectData> playerEffects = new Array<>();
        Array<EffectData> oppEffects = new Array<>();

        Map<DeckProxy, Pair<List<String>, List<String>>> deckProxyMapMap = null;
        DeckProxy deckProxy = null;
        if (chaosBattle) {
            deckProxyMapMap = DeckProxy.getAllQuestChallenges();
            deckProxy = Aggregates.random(deckProxyMapMap.keySet());
            //playerextras
            List<IPaperCard> playerCards = new ArrayList<>();
            for (String s : deckProxyMapMap.get(deckProxy).getLeft()) {
                playerCards.add(QuestUtil.readExtraCard(s));
            }
            humanPlayer.addExtraCardsOnBattlefield(playerCards);
        }

        if (eventData == null || eventData.eventRules.allowsItems) {
            //Collect and add items effects first.
            for (Long id : advPlayer.getEquippedItems()) {
                ItemData item = Current.player().getEquippedItem(id);
                if (item != null && item.effect != null) {
                    playerEffects.add(item.effect);
                    if (item.effect.opponent != null) oppEffects.add(item.effect.opponent);
                } else {
                    System.err.printf("Item %s not found.", id);
                }
            }
        }
        if (eventData == null || eventData.eventRules.allowsBlessings) {
            //Collect and add player blessings.
            if (advPlayer.getBlessing() != null) {
                playerEffects.add(advPlayer.getBlessing());
                if (advPlayer.getBlessing().opponent != null) oppEffects.add(advPlayer.getBlessing().opponent);
            }

            //Collect and add enemy effects (same as blessings but for individual enemies).
            if (enemy.effect != null) {
                oppEffects.add(enemy.effect);
                if (enemy.effect.opponent != null)
                    playerEffects.add(enemy.effect.opponent);
            }
        }
        //Collect and add dungeon-wide effects.
        if (dungeonEffect != null) {
            oppEffects.add(dungeonEffect);
            if (dungeonEffect.opponent != null)
                playerEffects.add(dungeonEffect.opponent);
        }

        addEffects(humanPlayer, playerEffects);

        currentEnemy = enemy.getData();
        boolean bossBattle = currentEnemy.boss;
        for (int i = 0; i < playerCount && currentEnemy != null; i++) {
            Deck deck;

            if (this.chaosBattle) { //random challenge for chaos mode
                if (deckProxyMapMap == null)
                    continue;
                //aiextras
                List<IPaperCard> aiCards = new ArrayList<>();
                for (String s : deckProxyMapMap.get(deckProxy).getRight()) {
                    aiCards.add(QuestUtil.readExtraCard(s));
                }
                this.AIExtras = aiCards;
                deck = deckProxy.getDeck();
            } else if (this.arenaBattleChallenge) {
                if (Config.instance().getConfigData().enableGeneticAI) {
                    deck = Aggregates.random(DeckProxy.getAllGeneticAIDecks()).getDeck();
                } else {
                    deck = currentEnemy.generateDeck(Current.player().isFantasyMode(), false);
                }
            } else if (this.eventData != null) {
                deck = eventData.nextOpponent.getDeck();
            } else {
                boolean useGeneticAI = Config.instance().getConfigData().enableGeneticAI && (Current.player().isUsingCustomDeck() || Current.player().isHardorInsaneDifficulty());
                deck = currentEnemy.copyPlayerDeck ? this.playerDeck : currentEnemy.generateDeck(Current.player().isFantasyMode(), useGeneticAI);
            }
            if (deck == null) {
                isDeckMissing = true;
                boolean canUseGeneticAI = Config.instance().getConfigData().enableGeneticAI;
                isDeckMissingMsg = "Deck for " + currentEnemy.getName() + " is missing! " + (this.eventData == null ? (canUseGeneticAI ? "Genetic AI deck will be used." : "Player deck will be used.") : "Player deck will be used.");
                System.err.println(isDeckMissingMsg);
                deck = this.eventData == null && canUseGeneticAI ? Aggregates.random(DeckProxy.getAllGeneticAIDecks()).getDeck() : this.playerDeck;
            }
            RegisteredPlayer aiPlayer = RegisteredPlayer.forVariants(playerCount, appliedVariants, deck, null, false, null, null);

            String aiProfile;
            if (Config.instance().getSettingData().enableGeminiAi) {
                String geminiModel = Config.instance().getSettingData().geminiModel;
                if (geminiModel != null && !geminiModel.isEmpty()) {
                    System.setProperty("forge.gemini.model", geminiModel);
                }
                boolean useVertex = Config.instance().getSettingData().useVertexAi;
                System.setProperty("forge.gemini.useVertex", String.valueOf(useVertex));
                if (useVertex) {
                    String proj = Config.instance().getSettingData().vertexProject;
                    if (proj != null && !proj.isEmpty())
                        System.setProperty("forge.gemini.vertexProject", proj);
                    String loc = Config.instance().getSettingData().vertexLocation;
                    if (loc != null && !loc.isEmpty())
                        System.setProperty("forge.gemini.vertexLocation", loc);
                }
                aiProfile = "Gemini";
            } else {
                aiProfile = selectAI(currentEnemy.ai);
            }
            LobbyPlayer enemyPlayer = GamePlayerUtil.createAiPlayer(currentEnemy.getName(), aiProfile);
            enemyPlayer.setName(enemy.getName()); //Override name if defined in the map.(only supported for 1 enemy atm)
            TextureRegion enemyAvatar = enemy.getAvatar(i);
            enemyAvatar.flip(true, false); //flip facing left
            FSkin.getAvatars().put(enemyAvatarKey + i, enemyAvatar);
            enemyPlayer.setAvatarIndex(enemyAvatarKey + i);
            aiPlayer.setPlayer(enemyPlayer);
            aiPlayer.setTeamNumber(currentEnemy.teamNumber);
            aiPlayer.setStartingLife(eventData != null ? eventData.eventRules.startingLife : Math.round((float) currentEnemy.life * advPlayer.getDifficulty().enemyLifeFactor));

            Array<EffectData> equipmentEffects = new Array<>();
            if (eventData != null && eventData.eventRules.allowsItems) {
                if (currentEnemy.equipment != null) {
                    for (String oppItem : currentEnemy.equipment) {
                        ItemData item = ItemListData.getItem(oppItem);
                        if (item == null)
                            continue;
                        equipmentEffects.add(item.effect);
                        if (item.effect.opponent != null)
                            playerEffects.add(item.effect.opponent);
                    }
                }
            }
            addEffects(aiPlayer, oppEffects);
            addEffects(aiPlayer, equipmentEffects);

            //add extra cards for challenger mode
            if (chaosBattle) {
                aiPlayer.addExtraCardsOnBattlefield(AIExtras);
            }

            players.add(aiPlayer);

            if (eventData == null) {
                Current.setLatestDeck(deck);
            }

            currentEnemy = currentEnemy.nextEnemy;
        }

        players.add(humanPlayer);

        if(eventData != null && eventData.draft != null) {
            for(RegisteredPlayer p : players)
                p.assignConspiracies();
        }

        final Map<RegisteredPlayer, IGuiGame> guiMap = new HashMap<>();
        guiMap.put(humanPlayer, MatchController.instance);
        if (netSession.isActiveHost()) {
            final ServerAdventureLobby serverLobby = netSession.serverLobby;
            for (int si = 1; si < serverLobby.getNumberOfSlots(); si++) {
                final LobbySlot slot = serverLobby.getSlot(si);
                if (slot.getType() != LobbySlotType.REMOTE) continue;
                final IGuiGame remoteGui = FServerManager.getInstance().getGui(si);
                if (remoteGui == null) continue;
                // Use stored player state if available; otherwise fall back to host values.
                final String[] state = serverLobby.getPlayerState(si);
                final Deck remoteDeck = buildRemoteDeck(state, playerDeck);
                final int remoteLife = resolveRemoteLife(state, eventData, advPlayer);
                final RegisteredPlayer remotePlayer = RegisteredPlayer.forVariants(
                        playerCount, appliedVariants, remoteDeck, null, false, null, null);
                final LobbyPlayerHuman remoteLobbyPlayer = new LobbyPlayerHuman(
                        slot.getName(), slot.getAvatarIndex(), slot.getSleeveIndex());
                remotePlayer.setPlayer(remoteLobbyPlayer);
                remotePlayer.setTeamNumber(0);
                remotePlayer.setStartingLife(remoteLife);
                applyRemotePlayerEffects(remotePlayer, state);
                players.add(remotePlayer);
                guiMap.put(remotePlayer, remoteGui);
            }
        }

        hostedMatch = MatchController.hostMatch();

        GameRules rules;

        if (eventData != null) {
            rules = new GameRules(eventData.eventRules.gameType);
            rules.setGamesPerMatch(eventData.eventRules.gamesPerMatch);
            bossBattle = false;
        } else {
            rules = new GameRules(GameType.Adventure);
            rules.setGamesPerMatch(enemy.getData().gamesPerMatch);
        }
        rules.setPlayForAnte(FModel.getPreferences().getPrefBoolean(ForgePreferences.FPref.UI_ANTE));
        rules.setMatchAnteRarity(FModel.getPreferences().getPrefBoolean(ForgePreferences.FPref.UI_ANTE_MATCH_RARITY));
        rules.setAnteIncludeBasicLands(FModel.getPreferences().getPrefBoolean(ForgePreferences.FPref.UI_ANTE_INCLUDE_BASIC_LANDS));
        rules.setManaBurn(false);
        rules.setWarnAboutAICards(false);

        //hostedMatch.setEndGameHook(() -> DuelScene.this.GameEnd());
        hostedMatch.startMatch(rules, appliedVariants, players, guiMap, bossBattle ? MusicPlaylist.BOSS : MusicPlaylist.MATCH);
        // In adventure multiplayer, GameLobby.startGame() is never called so
        // GameLobby.gameControllers is never populated.  GameServerHandler routes
        // incoming client messages (selectButtonOk, etc.) through getController(slotIndex),
        // which returns null when the map is empty — silently dropping all client inputs.
        // Populate the map here by matching game player names to lobby slot names.
        if (netSession.isActiveHost()) {
            System.out.println("[AdventureMP] DuelScene: populating GameLobby controllers for " + hostedMatch.getGame().getPlayers().size() + " players, " + netSession.serverLobby.getNumberOfSlots() + " slots");
            for (final Player p : hostedMatch.getGame().getPlayers()) {
                if (!(p.getController() instanceof PlayerControllerHuman pch)) {
                    System.out.println("[AdventureMP] DuelScene: skipping non-human player=" + p.getName());
                    continue;
                }
                final String name = p.getRegisteredPlayer().getPlayer().getName();
                boolean matched = false;
                for (int si = 0; si < netSession.serverLobby.getNumberOfSlots(); si++) {
                    final LobbySlot lobbySlot = netSession.serverLobby.getSlot(si);
                    System.out.println("[AdventureMP] DuelScene: checking slot=" + si + " slotName='" + lobbySlot.getName() + "' vs playerName='" + name + "'");
                    if (name.equals(lobbySlot.getName())) {
                        netSession.serverLobby.registerController(lobbySlot, pch);
                        System.out.println("[AdventureMP] DuelScene registered controller for slot=" + si + " name=" + name + " ctrl=" + pch.getClass().getSimpleName());
                        matched = true;
                        break;
                    }
                }
                if (!matched) {
                    System.out.println("[AdventureMP] DuelScene: WARNING no slot matched for human player name='" + name + "'");
                }
            }
        }
        MatchController.instance.setGameView(hostedMatch.getGameView());
        boolean showMessages = enemy.getData().boss || (enemy.getData().copyPlayerDeck && Current.player().isUsingCustomDeck());
        LoadingOverlay matchOverlay;
        if (chaosBattle || showMessages || isDeckMissing) {
            final FBufferedImage fb = getFBEnemyAvatar();
            String Intro = enemy.getBossIntro();
            if (Intro != null){
                bossDialogue = createFOption((Intro), enemy.getName(), fb, fb::dispose);
                }
                else {
                bossDialogue = createFOption(isDeckMissing ? isDeckMissingMsg : Forge.getLocalizer().getMessage("AdvBossIntro" + Aggregates.randomInt(1, 35)),
                enemy.getName(), fb, fb::dispose);
                }
            matchOverlay = new LoadingOverlay(() -> FThreads.delayInEDT(300, () -> FThreads.invokeInEdtNowOrLater(() ->
            bossDialogue.show())), false, true);
        } else {
            matchOverlay = new LoadingOverlay(null);
        }
        // NOTE: HostedMatch.startMatch() already calls setGui / setOriginalGameController /
        // openView for every human player via guiMap.  Repeating those calls here with
        // MatchController.instance for ALL PlayerControllerHuman instances was harmless in
        // single-player but in multiplayer it overwrote the remote client's RemoteClientGuiGame
        // with the host's MatchController — making the host handle the client's prompts and
        // showing the client's perspective on the host's screen (last openView wins).
        super.enter();
        matchOverlay.show();
    }

    private static final String PLACEHOLDER_MAIN = "Wastes";
    private static final String PLACEHOLDER_COMMANDER = "Atogatog";
    private static final String PLACEHOLDER_ATTRACTION = "Coin-Operated Pony";
    private static final String PLACEHOLDER_CONTRAPTION = "Automatic Fidget Spinner";

    private void applyAdventureDeckRules(DeckFormat format) {
        if(FModel.getPreferences().getPrefBoolean(ForgePreferences.FPref.DEV_MODE_ENABLED)
                && !FModel.getPreferences().getPrefBoolean(ForgePreferences.FPref.ENFORCE_DECK_LEGALITY))
            return;

        //Can't just keep the player from entering a battle if their deck is invalid. So instead we'll just edit their deck.
        CardPool mainSection = playerDeck.getMain(), attractions = playerDeck.get(DeckSection.Attractions), contraptions = playerDeck.get(DeckSection.Contraptions);

        if(format.hasCommander()) {
            applyAdventureCommandZoneRules(playerDeck, format);
        }

        removeExcessCopies(mainSection, format);
        removeExcessCopies(attractions, format);
        removeExcessCopies(contraptions, format);

        int mainSize = mainSection.countAll();

        int maxDeckSize = format == DeckFormat.Adventure ? Integer.MAX_VALUE : format.getMainRange().getMaximum();
        int minDeckSize = format == DeckFormat.Adventure ? Config.instance().getConfigData().minDeckSize : format.getMainRange().getMinimum();

        if(format.hasCommander() && playerDeck.has(DeckSection.Commander)) {
            //If they have a partner commander, it counts toward the 99.
            int commandExtras = Math.max(0, playerDeck.get(DeckSection.Commander).countAll() - 1);
            mainSize += commandExtras;
        }

        int excessCards = mainSize - maxDeckSize;
        if (excessCards > 0) {
            List<PaperCard> removals = Aggregates.random(mainSection.toFlatList(), excessCards);
            mainSection.removeAllFlat(removals);
        }

        int missingCards = minDeckSize - mainSize;
        if (missingCards > 0) //Replace unknown cards for a Wastes.
            mainSection.add(PLACEHOLDER_MAIN, missingCards);

        if(attractions != null && !attractions.isEmpty()) {
            int missingAttractions = 10 - attractions.countAll(); //TODO: These shouldn't be hard coded but DeckFormat's gonna need some reorganizing to fetch this dynamically
            if(missingAttractions > 0)
                attractions.add(PLACEHOLDER_ATTRACTION, missingAttractions);
        }
        if(contraptions != null && !contraptions.isEmpty()) {
            int missingContraptions = 15 - contraptions.countAll();
            if(missingContraptions > 0)
                contraptions.add(PLACEHOLDER_CONTRAPTION, missingContraptions);
        }
    }

    private static void removeExcessCopies(CardPool section, DeckFormat format) {
        if(section == null)
            return;
        Map<String, List<PaperCard>> removals = new HashMap<>();
        for(Map.Entry<PaperCard, Integer> e : section) {
            PaperCard card = e.getKey();
            String cardName = card.getCardName();
            if(removals.containsKey(cardName))
                continue; //Already processed.
            int amount = section.countByName(cardName);
            int limit = format.getMaxCardCopies(card);
            if(amount > limit) {
                removals.put(cardName, getItemsToRemove(section, cardName, amount - limit));
            }
        }
        for(List<PaperCard> list : removals.values())
            section.removeAllFlat(list);
    }

    private static List<PaperCard> getItemsToRemove(CardPool section, String cardName, int copies) {
        return section.toFlatList().stream()
                .filter(e -> e.getCardName().equals(cardName))
                .collect(StreamUtil.random(copies));
    }

    /**
     * Applies battle effects (items + blessings) serialized in PLAYER_STATE fields [5..9]
     * to the remote player's RegisteredPlayer slot on the host side.
     * state[5]=lifeMod, [6]=handMod, [7]=totalShards, [8]=battlefield card names, [9]=command zone card names.
     */
    private void applyRemotePlayerEffects(final RegisteredPlayer remotePlayer, final String[] state) {
        if (state == null || state.length < 10) return;
        try {
            final int lifeMod = Integer.parseInt(state[5]);
            final int handMod = Integer.parseInt(state[6]);
            final int shards  = Integer.parseInt(state[7]);
            final String bfNames  = state[8];
            final String cmdNames = state[9];

            if (lifeMod != 0)
                remotePlayer.setStartingLife(Math.max(1, remotePlayer.getStartingLife() + lifeMod));
            if (handMod != 0)
                remotePlayer.setStartingHand(remotePlayer.getStartingHand() + handMod);
            remotePlayer.setManaShards(shards);

            if (!bfNames.isEmpty()) {
                final Array<IPaperCard> cards = new Array<>(IPaperCard.class);
                for (final String name : bfNames.split("\n")) {
                    if (name.isEmpty()) continue;
                    PaperCard pc = FModel.getMagicDb().getCommonCards().getCard(name);
                    if (pc != null) { cards.add(pc); continue; }
                    try {
                        forge.item.PaperToken pt = FModel.getMagicDb().getAllTokens().getToken(name);
                        if (pt != null) cards.add(pt);
                    } catch (final Exception ignored) {}
                }
                if (!cards.isEmpty()) remotePlayer.addExtraCardsOnBattlefield(cards);
            }
            if (!cmdNames.isEmpty()) {
                final Array<IPaperCard> cards = new Array<>(IPaperCard.class);
                for (final String name : cmdNames.split("\n")) {
                    if (name.isEmpty()) continue;
                    PaperCard pc = FModel.getMagicDb().getCommonCards().getCard(name);
                    if (pc != null) { cards.add(pc); continue; }
                    try {
                        forge.item.PaperToken pt = FModel.getMagicDb().getAllTokens().getToken(name);
                        if (pt != null) cards.add(pt);
                    } catch (final Exception ignored) {}
                }
                if (!cards.isEmpty()) remotePlayer.addExtraCardsInCommandZone(cards);
            }
            if (lifeMod != 0 || handMod != 0 || !bfNames.isEmpty() || !cmdNames.isEmpty())
                remotePlayer.setEnableETBCountersEffect(true);
        } catch (final Exception e) {
            System.err.println("[AdventureMP] applyRemotePlayerEffects failed: " + e.getMessage());
        }
    }

    /**
     * Builds the deck for a remote player from their stored PLAYER_STATE.
     * Falls back to the host's own deck if no state has been received yet.
     */
    private static Deck buildRemoteDeck(final String[] state, final Deck fallback) {
        if (state == null || state.length < 4 || state[3].isEmpty()) return fallback;
        try {
            final forge.deck.CardPool pool = forge.deck.CardPool.fromCardList(
                    java.util.Arrays.asList(state[3].split("\n")));
            final Deck d = new Deck(state[0]);
            d.putSection(DeckSection.Main, pool);
            if (state.length >= 5 && state[4] != null && !state[4].isEmpty()) {
                final forge.deck.CardPool cmdPool = forge.deck.CardPool.fromCardList(
                        java.util.Arrays.asList(state[4].split("\n")));
                d.putSection(DeckSection.Commander, cmdPool);
            }
            return d;
        } catch (final Exception e) {
            System.err.println("[AdventureMP] buildRemoteDeck failed: " + e.getMessage());
            return fallback;
        }
    }

    /** Returns the starting life for a remote player from stored state, with fallback. */
    private static int resolveRemoteLife(final String[] state,
                                         final AdventureEventData eventData,
                                         final AdventurePlayer advPlayer) {
        if (eventData != null) return eventData.eventRules.startingLife;
        if (state != null && state.length >= 3) {
            try { return Integer.parseInt(state[2]); } catch (final NumberFormatException ignored) { }
        }
        return advPlayer.getLife();
    }

    private static void applyAdventureCommandZoneRules(Deck playerDeck, DeckFormat format) {
        CardPool commandPool = playerDeck.getOrCreate(DeckSection.Commander);

        //1. Validate command section.
        List<PaperCard> removals = new ArrayList<>();
        List<PaperCard> commanders = playerDeck.getCommanders(); //ordered flat list
        if (commanders.size() > 2) {
            removals.addAll(commanders.subList(2, commanders.size()));
            commanders = commanders.subList(0, 2);
        }
        if (!commanders.isEmpty()) {
            PaperCard mainCommander = commanders.get(0);
            if (!format.isLegalCommander(mainCommander.getRules()))
                removals.add(mainCommander);
            if (commanders.size() > 1) {
                PaperCard partnerCommander = commanders.get(1);
                if (removals.contains(mainCommander)) {
                    if (!format.isLegalCommander(partnerCommander.getRules()))
                        removals.add(partnerCommander); //Main is invalid but partner is valid.
                } else if (!mainCommander.getRules().canBePartnerCommanders(partnerCommander.getRules()))
                    removals.add(partnerCommander); //Invalid partnership.
            }
        }
        commandPool.removeAllFlat(removals);
        CardPool mainPool = playerDeck.getMain();
        mainPool.add(removals); //Dump all the removed cards into the main pool.

        //2. If you're missing a commander, install a terrible one.
        if(commandPool.isEmpty()) {
            commandPool.add(PLACEHOLDER_COMMANDER, 1);
        }

        //3. Validate quantities across command zone and main section
        //In other words if it's your commander, make sure there isn't a copy in your main deck.
        for(Map.Entry<PaperCard, Integer> e : commandPool) {
            PaperCard card = e.getKey();
            int limit = format.getMaxCardCopies(card);
            int amountMain = mainPool.countByName(card);
            if(amountMain > 0) {
                int amountCommand = commandPool.countByName(card);
                int toRemove = Math.max(0, (amountMain + amountCommand) - limit);
                if(toRemove > 0) {
                    mainPool.removeAllFlat(getItemsToRemove(mainPool, card.getCardName(), toRemove));
                }
            }
        }

        //4. Filter for color identity.
        byte cmdCI = 0;
        int wildColors = 0; //For Prismatic Piper and friends.
        for(PaperCard commander : playerDeck.getCommanders()) {
            cmdCI |= commander.getRules().getColorIdentity().getColor();
            wildColors += commander.getRules().getAddsWildCardColor() ? 1 : 0;
        }
        for(Map.Entry<PaperCard, Integer> e : mainPool) {
            PaperCard card = e.getKey();
            ColorSet missingColors = card.getRules().getColorIdentity().getMissingColors(cmdCI);
            if (missingColors.countColors() > 0) {
                if (missingColors.countColors() <= wildColors) {
                    wildColors -= missingColors.countColors();
                    cmdCI |= missingColors.getColor();
                } else {
                    mainPool.removeAll(card);
                }
            }
        }
    }

    @Override
    public FScreen getScreen() {
        return MatchController.getView();
    }

    public void initDuels(PlayerSprite playerSprite, EnemySprite enemySprite) {
        initDuels(playerSprite, enemySprite, false, null);
    }

    public void initDuels(PlayerSprite playerSprite, EnemySprite enemySprite, boolean isArena, AdventureEventData eventData) {
        this.player = playerSprite;
        this.enemy = enemySprite;
        this.isArena = isArena;
        this.eventData = eventData;
        if (eventData != null && eventData.eventRules == null)
            eventData.eventRules = new AdventureEventData.AdventureEventRules(AdventureEventController.EventFormat.Constructed, 1.0f);
        this.arenaBattleChallenge = isArena && Current.player().isHardorInsaneDifficulty();
        if (eventData != null && eventData.registeredDeck != null)
            this.playerDeck = (Deck) eventData.registeredDeck.copyTo("EventDeckCopy");
        else
            this.playerDeck = (Deck) Current.player().getSelectedDeck().copyTo("PlayerDeckCopy");
        this.chaosBattle = this.enemy.getData().copyPlayerDeck && Current.player().isFantasyMode();
        this.AIExtras.clear();
        this.playerExtras.clear();
    }

    private String selectAI(String ai) { //Decide opponent AI.
        String AI = ""; //Use user settings if it's null.
        if (ai != null) {
            AI = switch (ai.toLowerCase()) { //We use this way to ensure capitalization is exact.
                //We don't want misspellings here.
                case "default" -> "Default";
                case "reckless" -> "Reckless";
                case "cautious" -> "Cautious";
                case "experimental" -> "Experimental";
                case "gemini" -> "Gemini";
                default -> ""; //User settings.
            };
        }
        return AI;
    }

    private FBufferedImage getFBEnemyAvatar() {
        return new FBufferedImage(120, 120) {
            @Override
            protected void draw(Graphics g, float w, float h) {
                if (FSkin.getAvatars().get(enemyAvatarKey) != null)
                    g.drawImage(FSkin.getAvatars().get(enemyAvatarKey), 0, 0, w, h);
            }
        };
    }
}
